---
- name: Update cache before install
  apt:
    update_cache: yes
    cache_valid_time: 3600 # 5 minutos
  tags:
    - install

- name: Accept Java 8 License
  debconf: name='oracle-java8-installer' question='shared/accepted-oracle-license-v1-1' value='true' vtype='select'
  tags:
    - install

- name: Install Oracle Java 8
  apt: name={{item}} state=latest
  with_items:
          - oracle-java8-installer
          - ca-certificates
          - oracle-java8-set-default
  tags:
    - install


- name: Install Cassandra Server
  apt: name=cassandra state=present update_cache=yes
  tags:
    - install

- name: Enable cassandra server
  service:
          name: cassandra
          enabled: yes
  tags:
    - install
